services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lottery
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://postgres:5432/lottery -user=postgres -password=postgres -connectRetries=30 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy

  app:
    image: app-dev:latest
    container_name: app
    build:
      dockerfile: Dockerfile
      context: ./
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/lottery"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  pgdata:
